### ISSUE TITLE
patch for 684

### ISSUE THREAD

**Issue by FbQMTCivJr** [madbyte/d2ric#3]
Hey man,
needed your tool running, made some quick fixes nstuff, you can get the content for a diff.patch from

http://pastebin.com/esrRPKBE

changes:
enabled:
 - Oracle
 - Techies
 - Winter Wyvern

added:
 - Lotus Orb
 - Glimmer Cape
 - Guardian Greaves
 - Moon Shard
 - Silver Edge
 - Solar Crest
 - Octarine Core
 - Crimson guard (older dota patch)
 - upgraded BoT (ain't working - whyever)

updated:
 - prices of all items (no update of recipe)

other stuff:
 - sorted the item the way you'll see it in the shop ingame
 - moved around the items from 'secret shop' and 'base' as it happend in 6.84
 - disabled the item description, because there are many aged and i wasn't in mood to fix this too
 - used Teleport-Scroll icon for new items, because i can't base64 (why not using the images from "SteamApps\common\dota 2 beta\dota\resource\flash3\images\items"…
 - hope i haven't missed anything important

**Comment by madbyte** [comment]
thanks
i didn't know that someone is still using this tool :D
i will take a look at your changes an update my version to the current dota content

**Comment by FbQMTCivJr** [comment]
It's situational a very good tool e.g. if you watch someone's stream and think well that's a good build idea

and I like it much more as the ingame option :D
